// DoE 데이터셋 공통 엔진 — "데이터셋으로 시작"에 실데이터(Monton 2026 CBD를 공통 형식으로 옮긴 /datasets/cbd_odt)를 붙여 넣고,
// 실험표 단계에서 '실행 행렬 가져오기', 결과 단계에서 'CSV 붙여넣기'로 채워 모델·곡면까지 간다(LLM 없음).
import { chromium } from 'playwright-core';
const URL = process.argv[2] || 'http://localhost:8000/';
const b = await chromium.launch({ executablePath: process.env.CHROME, headless: true });
let fail = 0;
const ck = (n, ok, d = '') => { console.log(`${ok ? '  ✓' : '  ✗'} ${n}${d ? ' — ' + d : ''}`); if (!ok) fail++; };
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
if (process.env.GUEST) await ctx.request.post(new globalThis.URL(URL).origin + '/api/formula1/guest');
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.addInitScript(() => { localStorage.setItem('f1_guide_seen_v1', '1'); localStorage.removeItem('f1:d7study'); });
await p.goto(URL + '?v7', { waitUntil: 'networkidle' });
await p.waitForSelector('#d7w-dsbtn');
const ds = await p.evaluate(async () => (await fetch((window.__BASE__ || '') + '/api/doe-v7/datasets/cbd_odt')).json());
const status = () => p.locator('#d7w-ask h3 .d7-badge').first().textContent();
const waitStatus = async (x) => { await p.waitForFunction((v) => document.querySelector('#d7w-ask h3 .d7-badge')?.textContent === v, x, { timeout: 30000 }).catch(() => {}); return status(); };
const click = async (a) => { await p.click(`#d7w-ask [data-act="${a}"]`); await p.waitForFunction(() => ![...document.querySelectorAll('#d7w-ask button')].some((x) => x.disabled), null, { timeout: 30000 }); };
const fill = async () => { await p.click('#d7w-fill'); await p.waitForFunction(() => /채웠습니다/.test(document.getElementById('d7w-msg').textContent), null, { timeout: 15000 }); };

await p.click('#d7w-dsbtn');
const broken = { ...ds, source: {}, runs: ds.runs.slice(0, 5) };
await p.fill('#d7w-ds-text', JSON.stringify(broken));
await p.click('#d7w-ds-check');
await p.waitForFunction(() => /형식 오류/.test(document.getElementById('d7w-ds-out').textContent), null, { timeout: 15000 }).catch(() => {});
ck('형식 검사가 출처·run 수 오류를 모두 보여 줌', /출처/.test(await p.locator('#d7w-ds-out').textContent()) && /run은/.test(await p.locator('#d7w-ds-out').textContent()));
await p.fill('#d7w-ds-text', JSON.stringify(ds));
await p.click('#d7w-ds-check');
await p.waitForFunction(() => /형식 통과/.test(document.getElementById('d7w-ds-out').textContent), null, { timeout: 15000 }).catch(() => {});
ck('실데이터 형식 통과(요인 3 · 반응 3 · run 17)', /요인 3 · 반응 3 · run 17/.test(await p.locator('#d7w-ds-out').textContent()));
await p.click('#d7w-ds-go');
ck('데이터셋 study → HANDOFF_RECEIVED', (await waitStatus('HANDOFF_RECEIVED')) === 'HANDOFF_RECEIVED');
await click('handoff_confirm'); await fill(); await click('cqa_approve'); await click('fmea_approve');
await fill(); await click('factor_select'); await fill(); await click('range_approve');
ck('범위 승인 → DOE_PLAN_REVIEW', (await waitStatus('DOE_PLAN_REVIEW')) === 'DOE_PLAN_REVIEW');
await click('plan_import');
ck('실행 행렬 가져오기 → IMPORTED(설계군 BBD) · 교체 기록', (await status()) === 'DOE_PLAN_REVIEW' && /IMPORTED/.test(await p.locator('#d7w-body').textContent()) && /DOE_PLAN_REPLACED/.test(await p.locator('#d7w-body').textContent()));
await fill(); await click('plan_approve');
ck('실험표 승인 → WAITING_FOR_RESULTS', (await waitStatus('WAITING_FOR_RESULTS')) === 'WAITING_FOR_RESULTS');
const csv = ['Compression force,MCC,CCS,hardness_kgf,dt_s,friability_pct,batch_id,evidence_status',
  ...ds.runs.map((r) => [r.factors.X1, r.factors.X2, r.factors.X3, r.responses.hardness_kgf, r.responses.dt_s, r.responses.friability_pct, `"${r.label}"`, 'LITERATURE_DIRECT'].join(','))].join('\n');
await p.click('#d7w-form details.d7w-import summary');
await p.fill('#d7w-csv', csv);
await p.click('#d7w-csv-go');
await p.waitForFunction(() => /17행을 계획 run에 짝지었습니다/.test(document.getElementById('d7w-msg').textContent), null, { timeout: 15000 }).catch(() => {});
ck('CSV 17행이 요인 실제값으로 계획 run에 짝지어짐', /17행을 계획 run에 짝지었습니다/.test(await p.locator('#d7w-msg').textContent()));
ck('CSV는 표만 채움(제출 안 함)', (await status()) === 'WAITING_FOR_RESULTS');
await click('results_submit');
ck('결과 제출 → RESULT_QUALITY_REVIEW', (await waitStatus('RESULT_QUALITY_REVIEW')) === 'RESULT_QUALITY_REVIEW');
await click('results_confirm');
const blk = await p.locator('#d7w-ask').textContent();
ck('시험법 버전·독립성 없는 CSV는 RB12가 막음(RQ003·RQ008)', (await status()) === 'RESULT_QUALITY_REVIEW' && /RQ003/.test(blk) && /RQ008/.test(blk));
await click('results_revise');
await p.click('#d7w-form details.d7w-import summary');
await p.fill('#d7w-csv', csv.replace('evidence_status', 'evidence_status,test_method_version,replicate_independence').split('\n').map((l, i) => i ? l + ',as reported · Methods 2.2,INDEPENDENT_BATCH' : l).join('\n'));
await p.click('#d7w-csv-go');
await p.waitForFunction(() => /17행을 계획 run에 짝지었습니다/.test(document.getElementById('d7w-msg').textContent), null, { timeout: 15000 }).catch(() => {});
await click('results_submit');
await click('results_confirm');
ck('열을 채운 CSV → 대조 확인 → MODEL_FIT', (await waitStatus('MODEL_FIT')) === 'MODEL_FIT');
await p.waitForFunction(() => document.querySelectorAll('#d7w-rsg .rsg-plot .main-svg, #d7w-rsg .rsg-2d').length >= 9, null, { timeout: 90000 }).catch(() => {});
ck('곡면 격자 9칸', (await p.locator('#d7w-rsg .rsg-plot .main-svg, #d7w-rsg .rsg-2d').count()) >= 9);
ck('페이지 오류 없음', errs.length === 0, errs.join(' | '));
await b.close();
console.log(fail ? `\n${fail}건 실패` : '\nALL PASS');
process.exit(fail ? 1 : 0);
