"""DevelopmentStudy 상태기계 — 명세 v6.1 §5.1(메인)·§5.2(실행 서브사이클)·§5.4(전역 예외).

전이는 여기 표에 있는 것만 일어난다. `DevelopmentService._move()`가 매 전이를 이 표로
검사하고, 표 밖 전이는 예외가 아니라 `UNKNOWN` → WAITING_HUMAN_TRIAGE로 보낸다
(인계 문서 §6 Sprint 2 완료 기준: "전이표 밖 전이 발생 시 UNKNOWN → human triage").

규칙이 고르는 전이(reason code)는 `backtrack_routing_rules.csv`가 단일 진실원이고,
이 표는 "그 전이가 상태기계 그림에 존재하는가"를 한 번 더 확인하는 안전망이다. 승인·반려처럼
연구자가 고르는 전이는 규칙이 아니라 이 표만 따른다.
"""

from __future__ import annotations

from typing import Dict, FrozenSet, Set, Tuple

TERMINAL: FrozenSet[str] = frozenset({"COMPLETED", "CLOSED_SUPERSEDED", "INELIGIBLE"})
GLOBAL_EXCEPTIONS: FrozenSet[str] = frozenset({"WAITING_AUDIT_REVIEW", "WAITING_HUMAN_TRIAGE"})

_EDGES = """
HANDOFF_CREATED ENTRY_READINESS
ENTRY_READINESS WAITING_REQUIRED_DATA
WAITING_REQUIRED_DATA ENTRY_READINESS
ENTRY_READINESS INELIGIBLE
ENTRY_READINESS CQA_DRAFTING
CQA_DRAFTING WAITING_CQA_APPROVAL
WAITING_CQA_APPROVAL CQA_DRAFTING
WAITING_CQA_APPROVAL FMEA_DRAFTING
FMEA_DRAFTING WAITING_FMEA_APPROVAL
WAITING_FMEA_APPROVAL FMEA_DRAFTING
WAITING_FMEA_APPROVAL FACTOR_READINESS
FACTOR_READINESS WAITING_FACTOR_DATA
WAITING_FACTOR_DATA FACTOR_READINESS
FACTOR_READINESS RANGE_FINDING_RUNS
RANGE_FINDING_RUNS FACTOR_READINESS
FACTOR_READINESS STRATEGY_REVIEW
FACTOR_READINESS WAITING_FACTOR_APPROVAL
WAITING_FACTOR_APPROVAL FACTOR_READINESS
WAITING_FACTOR_APPROVAL DESIGN_SELECTION
DESIGN_SELECTION SCREENING_PLANNING
DESIGN_SELECTION RSM_PLANNING
SCREENING_PLANNING DESIGN_REPLAN
SCREENING_PLANNING WAITING_SCREENING_APPROVAL
WAITING_SCREENING_APPROVAL SCREENING_PLANNING
WAITING_SCREENING_APPROVAL SCREENING_EXECUTION
SCREENING_EXECUTION SCREENING_ANALYSIS
SCREENING_ANALYSIS SCREENING_AUGMENTATION
SCREENING_AUGMENTATION WAITING_SCREENING_APPROVAL
SCREENING_ANALYSIS FACTOR_READINESS
SCREENING_ANALYSIS RSM_PLANNING
SCREENING_ANALYSIS STRATEGY_REVIEW
SCREENING_ANALYSIS DIAGNOSING
RSM_PLANNING DESIGN_REPLAN
RSM_PLANNING WAITING_RSM_APPROVAL
WAITING_RSM_APPROVAL RSM_PLANNING
WAITING_RSM_APPROVAL RSM_EXECUTION
RSM_EXECUTION MODEL_VALIDATION
MODEL_VALIDATION WAITING_MODEL_APPROVAL
WAITING_MODEL_APPROVAL MODEL_VALIDATION
WAITING_MODEL_APPROVAL RSM_AUGMENTATION
MODEL_VALIDATION RSM_AUGMENTATION
MODEL_VALIDATION DIAGNOSING
MODEL_VALIDATION REGION_COMPUTATION
RSM_AUGMENTATION WAITING_RSM_APPROVAL
DESIGN_REPLAN DESIGN_SELECTION
DESIGN_REPLAN FACTOR_READINESS
REGION_COMPUTATION STRATEGY_REVIEW
REGION_COMPUTATION WAITING_REGION_APPROVAL
WAITING_REGION_APPROVAL REGION_COMPUTATION
WAITING_REGION_APPROVAL VERIFICATION_PLANNING
VERIFICATION_PLANNING WAITING_VERIFICATION_PLAN_APPROVAL
WAITING_VERIFICATION_PLAN_APPROVAL VERIFICATION_PLANNING
WAITING_VERIFICATION_PLAN_APPROVAL VERIFICATION_EXECUTION
VERIFICATION_EXECUTION VERIFICATION_GATE
VERIFICATION_GATE WAITING_FINAL_APPROVAL
VERIFICATION_GATE RSM_AUGMENTATION
VERIFICATION_GATE DIAGNOSING
WAITING_FINAL_APPROVAL VERIFICATION_PLANNING
WAITING_FINAL_APPROVAL COMPLETED
DIAGNOSING WAITING_DISCRIMINATING_TESTS
WAITING_DISCRIMINATING_TESTS DIAGNOSING
DIAGNOSING WAITING_HUMAN_TRIAGE
DIAGNOSING REFLECTING
REFLECTING WAITING_DIRECTIVE_APPROVAL
WAITING_DIRECTIVE_APPROVAL DIAGNOSING
WAITING_DIRECTIVE_APPROVAL RSM_AUGMENTATION
WAITING_DIRECTIVE_APPROVAL FACTOR_READINESS
WAITING_DIRECTIVE_APPROVAL DESIGN_SELECTION
WAITING_DIRECTIVE_APPROVAL CLOSED_SUPERSEDED
STRATEGY_REVIEW FACTOR_READINESS
STRATEGY_REVIEW CLOSED_SUPERSEDED
"""

MAIN_TRANSITIONS: FrozenSet[Tuple[str, str]] = frozenset(
    tuple(line.split()) for line in _EDGES.strip().splitlines() if line.strip()
)

# 실행 서브사이클(§5.2) — run 단위 상태. EXIT_* 는 메인 상태로 연결된다.
RUN_TRANSITIONS: FrozenSet[Tuple[str, str]] = frozenset({
    ("RUN_SHEET_COMPILE", "WAITING_RUN_DATA"), ("WAITING_RUN_DATA", "RUN_SHEET_COMPILE"),
    ("RUN_SHEET_COMPILE", "EXIT_REPLAN"), ("RUN_SHEET_COMPILE", "WAITING_BATCH_RESULTS"),
    ("WAITING_BATCH_RESULTS", "WAITING_RESULT_CONFIRMATION"),
    ("WAITING_RESULT_CONFIRMATION", "WAITING_BATCH_RESULTS"),
    ("WAITING_RESULT_CONFIRMATION", "RESULT_QUALITY_GATE"),
    ("RESULT_QUALITY_GATE", "WAITING_BATCH_RESULTS"), ("RESULT_QUALITY_GATE", "EXIT_DIAGNOSIS"),
    ("RESULT_QUALITY_GATE", "EXIT_ANALYSIS"),
})
RUN_EXIT_TO_MAIN: Dict[str, str] = {"EXIT_REPLAN": "DESIGN_REPLAN", "EXIT_DIAGNOSIS": "DIAGNOSING"}

# 서브사이클을 run별로 돌리는 메인 상태 (§5.2 첫 문단)
EXECUTION_STATES: FrozenSet[str] = frozenset({
    "RANGE_FINDING_RUNS", "SCREENING_EXECUTION", "RSM_EXECUTION", "VERIFICATION_EXECUTION",
    "WAITING_DISCRIMINATING_TESTS",
})

# 모든 WAITING_*_APPROVAL은 승인·반려 전이를 가진다 (§15 Orchestration 인수 테스트).
APPROVAL_STATES: Dict[str, Tuple[str, str]] = {
    # 상태: (승인 시 다음 상태, 반려 시 다음 상태)
    "WAITING_CQA_APPROVAL": ("FMEA_DRAFTING", "CQA_DRAFTING"),
    "WAITING_FMEA_APPROVAL": ("FACTOR_READINESS", "FMEA_DRAFTING"),
    "WAITING_FACTOR_APPROVAL": ("DESIGN_SELECTION", "FACTOR_READINESS"),
    "WAITING_SCREENING_APPROVAL": ("SCREENING_EXECUTION", "SCREENING_PLANNING"),
    "WAITING_RSM_APPROVAL": ("RSM_EXECUTION", "RSM_PLANNING"),
    "WAITING_MODEL_APPROVAL": ("MODEL_VALIDATION", "RSM_AUGMENTATION"),
    "WAITING_REGION_APPROVAL": ("VERIFICATION_PLANNING", "REGION_COMPUTATION"),
    "WAITING_VERIFICATION_PLAN_APPROVAL": ("VERIFICATION_EXECUTION", "VERIFICATION_PLANNING"),
    "WAITING_FINAL_APPROVAL": ("COMPLETED", "VERIFICATION_PLANNING"),
    "WAITING_DIRECTIVE_APPROVAL": ("<directive>", "DIAGNOSING"),
}

# 화면 stepper용 — 연구자가 보는 큰 단계. 상태 하나는 정확히 한 단계에 속한다.
PHASES = [
    ("handoff", "Handoff·진입", {"HANDOFF_CREATED", "ENTRY_READINESS", "WAITING_REQUIRED_DATA", "INELIGIBLE"}),
    ("cqa", "CQA", {"CQA_DRAFTING", "WAITING_CQA_APPROVAL"}),
    ("fmea", "FMEA", {"FMEA_DRAFTING", "WAITING_FMEA_APPROVAL"}),
    ("factor", "요인·수준", {"FACTOR_READINESS", "WAITING_FACTOR_DATA", "RANGE_FINDING_RUNS",
                             "WAITING_FACTOR_APPROVAL", "STRATEGY_REVIEW"}),
    ("design", "설계", {"DESIGN_SELECTION", "SCREENING_PLANNING", "RSM_PLANNING", "DESIGN_REPLAN",
                       "WAITING_SCREENING_APPROVAL", "WAITING_RSM_APPROVAL", "SCREENING_AUGMENTATION",
                       "RSM_AUGMENTATION"}),
    ("runs", "실행·결과", {"SCREENING_EXECUTION", "RSM_EXECUTION", "SCREENING_ANALYSIS"}),
    ("model", "모델", {"MODEL_VALIDATION", "WAITING_MODEL_APPROVAL"}),
    ("region", "잠정 영역", {"REGION_COMPUTATION", "WAITING_REGION_APPROVAL"}),
    ("verify", "확인배치", {"VERIFICATION_PLANNING", "WAITING_VERIFICATION_PLAN_APPROVAL",
                         "VERIFICATION_EXECUTION", "VERIFICATION_GATE", "WAITING_FINAL_APPROVAL"}),
    ("done", "VERIFIED", {"COMPLETED"}),
]
SIDE_STATES = {"DIAGNOSING", "WAITING_DISCRIMINATING_TESTS", "REFLECTING", "WAITING_DIRECTIVE_APPROVAL",
               "WAITING_HUMAN_TRIAGE", "WAITING_AUDIT_REVIEW", "CLOSED_SUPERSEDED"}


def allowed(src: str, dst: str) -> bool:
    if dst in GLOBAL_EXCEPTIONS:
        return src not in TERMINAL
    return (src, dst) in MAIN_TRANSITIONS


def phase_of(state: str) -> str:
    for key, _, members in PHASES:
        if state in members:
            return key
    return "side"


def all_states() -> Set[str]:
    out = {s for edge in MAIN_TRANSITIONS for s in edge}
    return out | set(GLOBAL_EXCEPTIONS)
